source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '8.0'

target 'Segment-Ambassador_Example' do
  pod "Segment-Ambassador", :path => "../"
  
  pod 'Ambassador'
end

target 'Segment-Ambassador_Tests' do
  pod "Segment-Ambassador", :path => "../"

  pod 'OCMockito'
  pod 'Specta'
  pod 'Expecta'
end


